volumes:
  pgdata:
  static:
  media:

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./docker/env/.env.dev.db

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - docker/env/.env.dev
    expose:
      - 6379
    volumes:
      - ./docker/redis/data:/data

  django:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: django
    env_file:
      - ./docker/env/.env.dev
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis
    command: sh -c  "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django

  celery-worker:
    build: .
    container_name: celery-worker
    restart: always
    env_file:
      - docker/env/.env.dev
    volumes:
      - ./:/app
      - media:/app/media
    command: celery -A csin_coin worker --loglevel=info --logfile=./docker/logs/celery-worker.log
    depends_on:
      - redis
